---
name: Run gametests

"on":
  workflow_dispatch:

jobs:
  run:
    name: Build and run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build --stacktrace
      - name: Create mods dir
        run: mkdir -p run/mods
      - name: List mod files
        run: ls build/libs
      - name: Copy mod jar
        run: cp build/libs/clientgametest-1.20.4-1.0.0-fabric.jar run/mods
      - name: Run game
        timeout-minutes: 3
        uses: headlesshq/mc-runtime-test@3.0.0
        with:
          mc: 1.20.4
          modloader: fabric
          regex: .*fabric.*
          java: 21
          mc-runtime-test: fabric
          headlessmc-command: --jvm "-Djava.awt.headless=true -DMcRuntimeGameTestMinExpectedGameTests=1"
          fabric-api: 0.97.0
          fabric-gametest-api: 1.3.5+85d85a934f
